numeros-aleatorios: 15

filas:
  -
    id: 0
    servidores: 2
    capacidade: 4
    chegada-inicial: 3.0
    chegada-minima: 2.0
    chegada-maxima: 3.0
    saida-minima: 4.0
    saida-maxima: 7.0
  -
    id: 1
    servidores: 1
    capacidade: -1
    saida-minima: 4.0
    saida-maxima: 8.0

redes:
  -
    origem: 0
    destino: 1
    probabilidade: 0.7






