numeros-aleatorios: 100000

filas:
  -
    id: 0
    servidores: 2
    capacidade: 3
    chegada-inicial: 2.5
    chegada-minima: 2.0
    chegada-maxima: 3.0
    saida-minima: 2.0
    saida-maxima: 5.0
  -
    id: 1
    servidores: 1
    capacidade: 3
    saida-minima: 3.0
    saida-maxima: 5.0

redes:
  -
    origem: 0
    destino: 1
    probabilidade: 1.0






